resources:

  - name: nodeRepo
    type: gitRepo
    # replace dr_github with your GitHub integration name
    integration: github
    pointer:
      # replace with source code location (e.g. GitHub) where you cloned this
      # sample project.
      sourceName: ambarish2012/basic-node-windows
      branch: master

jobs:

  - name: build_node
    type: runSh
    runtime:
      nodePool: custom__x86_64__WindowsServer_2016
      container: true
    steps:
      - IN: nodeRepo
      - TASK:
          name: build_node
          runtime:
            options:
              imageName: "stefanscherer/node-windows"
              imageTag: "9.4.0-nanoserver-2016"
          script:
            - shippable_retry npm install
            
